from typing import Any, Type

from django_skeleton.db.models import ModelBase
from django_skeleton.db.models.managers import BaseManager
from django_skeleton.db.models.options import Options

class BaseModel(type):
    def __new__(cls, name: str, bases: tuple, attrs: dict) -> Type: ...
    @classmethod
    def from_db(cls, db, field_names: list, values: list) -> BaseModel: ...
    def add_to_class(cls, name: str, value: Any) -> None: ...


class Model(metaclass=ModelBase):
    objects: BaseManager = ...
    _meta: Options = ...

    def __init__(self, *args, **kwargs): ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
