from django_skeleton.db.models.fields import Field
from django_skeleton.db.models.sql.compiler import SQLCompiler
from django_skeleton.db.utils import BaseConnectionHandler

class BaseExpression:
    def __init__(self, output_field: Field = None) -> None: ...
    

class Expression(BaseExpression): ...


class Col(Expression):
    contains_column_references: bool = ...
    possibly_multivalued: bool = ...
    def __init__(self, alias: str, target: Field, output_field: Field = None): ...
    def as_sql(self, compiler: SQLCompiler, connection: BaseConnectionHandler): ...
