from typing import Iterator, Optional, Type

from django_skeleton.db.models import Model
from django_skeleton.db.models.sql.query import Query


class QuerySet:
    model: Type = ...
    _query: Query = ...
    def __init__(self, model: Optional[Model] = ..., query: Optional[Query] = None, using: Optional[str] = ..., hints: Optional[dict] = ...) -> None: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator: ...
    def count(self) -> int: ...
    def get(self, **kwargs) -> QuerySet: ...
    def filter(self, *args, **kwargs) -> QuerySet: ...
